on:
  workflow_dispatch:
  push:

name: build-r-package

jobs:
  check-versions:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - {os: macos-latest}
          - {os: ubuntu-latest}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - if: runner.os == 'Linux'
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable \
          && sudo apt-get update \
          && sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev libsqlite3-dev

      - if: runner.os == 'macOS'
        run: |
          brew install pkg-config \
          && brew install gdal 
