on:
  workflow_dispatch:
  push:

name: build-r-package

permissions:
  contents: write

jobs:
  check-versions:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          # - {os: macos-latest}
          - {os: ubuntu-latest}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Prep Linux
        # if: runner.os == 'Linux'
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable \
          && sudo apt-get update \
          && sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev libsqlite3-dev \
          && wget "https://raw.githubusercontent.com/r-universe-org/actions/refs/heads/v9/getdeps.R" \
          && Rscript -e "utils::setRepositories(ind = 0, addURLs = c(CRAN = 'https://packagemanager.posit.co/cran/latest'))"

      - name: Make sf on Linux
        run: |
          mkdir sf \
          && cd sf \
          && wget -O sf.zip "https://r-spatial.r-universe.dev/api/snapshot/zip?types=src&packages=sf" \
          && unzip sf.zip \
          && cd src/contrib \
          && sf_file="$(ls | grep 'sf_.*[0-9]\.tar\.gz$')" \
          && echo $sf_file \
          && sudo Rscript ../../../getdeps.R $sf_file \
          && R CMD INSTALL --build $sf_file \
          && rm -fv ../../../sf*linux* \
          && mv sf*linux* ../../..

      - name: Add to repo
        run: |
           git config --global user.name 'gha update bot'
           git config --global user.email 'mhpob@users.noreply.github.com'
           git add -u
           git add *.tar.gz
           git commit -m "[auto] Build packages"
           git push

      # - name: Make terra on Linux
      #   run: |
      #     cd ../../.. \
      #     && mkdir terra \
      #     && cd terra \
      #     && wget -O terra.zip "https://rspatial.r-universe.dev/api/snapshot/zip?types=src&packages=terra" \
      #     && unzip sf.zip \
      #     && cd src/contrib \
      #     && terra_file="$(ls | grep 'terra_.*[0-9]\.tar\.gz$')" \
      #     && sudo Rscript ../../getdeps.R $terra_file


      # - if: runner.os == 'macOS'
      #   run: |
      #     brew install pkg-config \
      #     && brew install gdal 
